### ISSUE TITLE
What is GLUS?

### ISSUE THREAD

**Issue by maratsarbasov** [McNopper/GLUS#4]
Can you write in README what is GLUS and why I need it?
Thanks

**Comment by McNopper** [comment]
GLUS - Cross platform and cross graphic library utilities

The cross platform and cross Graphic Library UtilitieS (GLUS) is an open-source C library, which provides a hardware (HW) and operating system (OS) abstraction plus many functions usually needed for graphics programming using OpenGL, OpenGL ES or OpenVG.

https://www.opengl.org/sdk/libs/GLUS/
