### ISSUE TITLE
Is the GLUS hosted content on opengl.org/sdk still needed?

### ISSUE THREAD

**Issue by oddhack** [McNopper/GLUS#6]
We're restructuring the website and trying to eliminate the hosted content. Do you still need to host GLUS there, or will a link to this project suffice?

**Comment by McNopper** [comment]
Please ZIP the GLUS content on opengl.org and send it to me. Then, a link to McNopper/GLUS is okay.

**Comment by oddhack** [comment]
Attached to this issue. Looks like mostly docs.
[glus.zip](https://github.com/McNopper/GLUS/files/752449/glus.zip)

**Comment by McNopper** [comment]
Will update my site the coming days. Will close, as soon as updated.

**Comment by McNopper** [comment]
Uploaded, please link to https://github.com/McNopper/GLUS
